// ═══════════════════════════════════════════════════════════════
// MERCHANT DATABASE - Instant Offline Auto-Suggest
// ═══════════════════════════════════════════════════════════════
// Popular merchants with their exact reward categories and brand
// colors for beautiful native UI rendering. ~200+ entries.

export let MERCHANT_DATABASE = [
  // ── Dining & Fast Food ──
  { id: "mcdonalds", name: "McDonald's", category: "dining", color: "#E31837" },
  { id: "starbucks", name: "Starbucks", category: "dining", color: "#00704A" },
  { id: "chipotle", name: "Chipotle", category: "dining", color: "#451400" },
  { id: "chick_fil_a", name: "Chick-fil-A", category: "dining", color: "#E51636" },
  { id: "wendys", name: "Wendy's", category: "dining", color: "#E20030" },
  { id: "burger_king", name: "Burger King", category: "dining", color: "#DA291C" },
  { id: "taco_bell", name: "Taco Bell", category: "dining", color: "#702082" },
  { id: "subway", name: "Subway", category: "dining", color: "#008C15" },
  { id: "dominos", name: "Domino's Pizza", category: "dining", color: "#006491" },
  { id: "pizza_hut", name: "Pizza Hut", category: "dining", color: "#EE3124" },
  { id: "panera", name: "Panera Bread", category: "dining", color: "#4B713D" },
  { id: "panda_express", name: "Panda Express", category: "dining", color: "#D31145" },
  { id: "dunkin", name: "Dunkin'", category: "dining", color: "#FF671F" },
  { id: "olive_garden", name: "Olive Garden", category: "dining", color: "#2B4726" },
  { id: "applebees", name: "Applebee's", category: "dining", color: "#C8102E" },
  { id: "texas_roadhouse", name: "Texas Roadhouse", category: "dining", color: "#E03A3E" },
  { id: "buffalo_wild_wings", name: "Buffalo Wild Wings", category: "dining", color: "#FFC20E" },
  { id: "outback", name: "Outback Steakhouse", category: "dining", color: "#BA0C2F" },
  { id: "doordash", name: "DoorDash", category: "dining", color: "#FF3008" },
  { id: "uber_eats", name: "Uber Eats", category: "dining", color: "#06C167" },
  { id: "grubhub", name: "Grubhub", category: "dining", color: "#F06428" },
  { id: "five_guys", name: "Five Guys", category: "dining", color: "#C8102E" },
  { id: "in_n_out", name: "In-N-Out Burger", category: "dining", color: "#DA291C" },
  { id: "shake_shack", name: "Shake Shack", category: "dining", color: "#2D2926" },
  { id: "ihop", name: "IHOP", category: "dining", color: "#005DAA" },
  { id: "dennys", name: "Denny's", category: "dining", color: "#FFC72C" },
  { id: "waffle_house", name: "Waffle House", category: "dining", color: "#FDB913" },
  { id: "wingstop", name: "Wingstop", category: "dining", color: "#007A33" },
  { id: "raising_canes", name: "Raising Cane's", category: "dining", color: "#E51636" },
  { id: "popeyes", name: "Popeyes", category: "dining", color: "#F47B20" },
  { id: "kfc", name: "KFC", category: "dining", color: "#F40027" },
  { id: "sonic", name: "Sonic Drive-In", category: "dining", color: "#003F87" },
  { id: "jack_in_the_box", name: "Jack in the Box", category: "dining", color: "#E31837" },
  { id: "arbys", name: "Arby's", category: "dining", color: "#D22630" },
  { id: "papa_johns", name: "Papa Johns", category: "dining", color: "#006341" },
  { id: "little_caesars", name: "Little Caesars", category: "dining", color: "#EA6A22" },
  { id: "cracker_barrel", name: "Cracker Barrel", category: "dining", color: "#86652B" },
  { id: "red_lobster", name: "Red Lobster", category: "dining", color: "#B51A25" },
  { id: "cheesecake_factory", name: "The Cheesecake Factory", category: "dining", color: "#8B6914" },
  { id: "chilis", name: "Chili's", category: "dining", color: "#006341" },
  { id: "tgi_fridays", name: "TGI Friday's", category: "dining", color: "#C8102E" },
  { id: "sweetgreen", name: "Sweetgreen", category: "dining", color: "#2D5E1E" },
  { id: "cava", name: "CAVA", category: "dining", color: "#2C5234" },
  { id: "noodles_co", name: "Noodles & Company", category: "dining", color: "#C8102E" },

  // ── Groceries ──
  { id: "walmart_grocery", name: "Walmart Grocery", category: "groceries", color: "#0071CE" },
  { id: "target_grocery", name: "Target Grocery", category: "groceries", color: "#E31837" },
  { id: "kroger", name: "Kroger", category: "groceries", color: "#005CAB" },
  { id: "publix", name: "Publix", category: "groceries", color: "#3B7321" },
  { id: "safeway", name: "Safeway", category: "groceries", color: "#E31837" },
  { id: "albertsons", name: "Albertsons", category: "groceries", color: "#00478F" },
  { id: "whole_foods", name: "Whole Foods Market", category: "groceries", color: "#00674B" },
  { id: "trader_joes", name: "Trader Joe's", category: "groceries", color: "#CE2029" },
  { id: "aldi", name: "ALDI", category: "groceries", color: "#003E69" },
  { id: "heb", name: "H-E-B", category: "groceries", color: "#E2231A" },
  { id: "meijer", name: "Meijer", category: "groceries", color: "#003A70" },
  { id: "wegmans", name: "Wegmans", category: "groceries", color: "#AE132A" },
  { id: "instacart", name: "Instacart", category: "groceries", color: "#0B8C3A" },
  { id: "food_lion", name: "Food Lion", category: "groceries", color: "#E21837" },
  { id: "giant_eagle", name: "Giant Eagle", category: "groceries", color: "#C8102E" },
  { id: "sprouts", name: "Sprouts Farmers Market", category: "groceries", color: "#6AAE4C" },
  { id: "stop_shop", name: "Stop & Shop", category: "groceries", color: "#E11A2C" },
  { id: "winco", name: "WinCo Foods", category: "groceries", color: "#003572" },
  { id: "harris_teeter", name: "Harris Teeter", category: "groceries", color: "#D22630" },
  { id: "piggly_wiggly", name: "Piggly Wiggly", category: "groceries", color: "#E31837" },
  { id: "food4less", name: "Food 4 Less", category: "groceries", color: "#C8102E" },
  { id: "giant_food", name: "Giant Food", category: "groceries", color: "#592C82" },
  { id: "shoprite", name: "ShopRite", category: "groceries", color: "#C8102E" },

  // ── Wholesale Clubs ──
  { id: "costco", name: "Costco", category: "wholesale_clubs", color: "#E31837" },
  { id: "sams_club", name: "Sam's Club", category: "wholesale_clubs", color: "#0067A0" },
  { id: "bjs_wholesale", name: "BJ's Wholesale Club", category: "wholesale_clubs", color: "#E31837" },
  { id: "target", name: "Target", category: "wholesale_clubs", color: "#E31837" },
  { id: "walmart_supercenter", name: "Walmart Supercenter", category: "wholesale_clubs", color: "#0071CE" },

  // ── Online Retailers ──
  { id: "amazon", name: "Amazon", category: "online_shopping", color: "#FF9900" },
  { id: "ebay", name: "eBay", category: "online_shopping", color: "#E53238" },
  { id: "etsy", name: "Etsy", category: "online_shopping", color: "#F1641E" },
  { id: "wayfair", name: "Wayfair", category: "online_shopping", color: "#30195C" },
  { id: "overstock", name: "Overstock", category: "online_shopping", color: "#C7202C" },
  { id: "newegg", name: "Newegg", category: "online_shopping", color: "#ECA313" },
  { id: "zappos", name: "Zappos", category: "online_shopping", color: "#003953" },
  { id: "shein", name: "SHEIN", category: "online_shopping", color: "#000000" },
  { id: "temu", name: "Temu", category: "online_shopping", color: "#FF6600" },
  { id: "asos", name: "ASOS", category: "online_shopping", color: "#000000" },
  { id: "walmart_com", name: "Walmart.com", category: "online_shopping", color: "#0071CE" },
  { id: "stockx", name: "StockX", category: "online_shopping", color: "#006340" },
  { id: "poshmark", name: "Poshmark", category: "online_shopping", color: "#C8102E" },
  { id: "thredup", name: "ThredUp", category: "online_shopping", color: "#006341" },
  { id: "mercari", name: "Mercari", category: "online_shopping", color: "#4DC3FF" },

  // ── General Retail (catch-all) — Physical stores don't code as online shopping ──
  { id: "apple_store", name: "Apple Store", category: "catch-all", color: "#000000" },
  { id: "best_buy", name: "Best Buy", category: "catch-all", color: "#0046BE" },
  { id: "home_depot", name: "The Home Depot", category: "catch-all", color: "#F96302" },
  { id: "lowes", name: "Lowe's", category: "catch-all", color: "#004990" },
  { id: "ikea", name: "IKEA", category: "catch-all", color: "#0051BA" },
  { id: "sephora", name: "Sephora", category: "catch-all", color: "#000000" },
  { id: "ulta", name: "Ulta Beauty", category: "catch-all", color: "#F47D30" },
  { id: "macys", name: "Macy's", category: "catch-all", color: "#E21A2C" },
  { id: "nordstrom", name: "Nordstrom", category: "catch-all", color: "#000000" },
  { id: "nike", name: "Nike", category: "catch-all", color: "#111111" },
  { id: "adidas", name: "adidas", category: "catch-all", color: "#000000" },
  { id: "lululemon", name: "lululemon", category: "catch-all", color: "#D22030" },
  { id: "chewy", name: "Chewy", category: "online_shopping", color: "#1C4CBF" },
  { id: "petsmart", name: "PetSmart", category: "catch-all", color: "#C8102E" },
  { id: "petco", name: "Petco", category: "catch-all", color: "#0079C2" },
  { id: "zara", name: "Zara", category: "catch-all", color: "#000000" },
  { id: "hm", name: "H&M", category: "catch-all", color: "#E50010" },
  { id: "uniqlo", name: "Uniqlo", category: "catch-all", color: "#FF0000" },
  { id: "under_armour", name: "Under Armour", category: "catch-all", color: "#1D1D1D" },
  { id: "new_balance", name: "New Balance", category: "catch-all", color: "#CF0A2C" },
  { id: "crate_barrel", name: "Crate & Barrel", category: "catch-all", color: "#000000" },
  { id: "pottery_barn", name: "Pottery Barn", category: "catch-all", color: "#000000" },
  { id: "williams_sonoma", name: "Williams-Sonoma", category: "catch-all", color: "#000000" },
  { id: "rh", name: "Restoration Hardware", category: "catch-all", color: "#000000" },
  { id: "gamestop", name: "GameStop", category: "catch-all", color: "#E31837" },
  { id: "foot_locker", name: "Foot Locker", category: "catch-all", color: "#E31837" },
  { id: "finish_line", name: "Finish Line", category: "catch-all", color: "#0033A0" },
  { id: "champs", name: "Champs Sports", category: "catch-all", color: "#C8102E" },
  { id: "dicks", name: "DICK'S Sporting Goods", category: "catch-all", color: "#006400" },
  { id: "rei", name: "REI", category: "catch-all", color: "#000000" },
  { id: "hollister", name: "Hollister", category: "catch-all", color: "#000000" },
  { id: "abercrombie", name: "Abercrombie & Fitch", category: "catch-all", color: "#000000" },
  { id: "american_eagle", name: "American Eagle", category: "catch-all", color: "#000000" },
  { id: "urban_outfitters", name: "Urban Outfitters", category: "catch-all", color: "#000000" },
  { id: "anthropologie", name: "Anthropologie", category: "catch-all", color: "#000000" },
  { id: "old_navy", name: "Old Navy", category: "catch-all", color: "#000080" },
  { id: "gap", name: "Gap", category: "catch-all", color: "#000066" },
  { id: "banana_republic", name: "Banana Republic", category: "catch-all", color: "#000000" },
  { id: "jcrew", name: "J.Crew", category: "catch-all", color: "#000000" },
  { id: "express", name: "Express", category: "catch-all", color: "#000000" },
  { id: "forever_21", name: "Forever 21", category: "catch-all", color: "#000000" },
  { id: "tj_maxx", name: "T.J. Maxx", category: "catch-all", color: "#D22630" },
  { id: "marshalls", name: "Marshalls", category: "catch-all", color: "#005CAB" },
  { id: "burlington", name: "Burlington", category: "catch-all", color: "#E31837" },
  { id: "ross", name: "Ross Dress for Less", category: "catch-all", color: "#005CAB" },
  { id: "jcpenney", name: "JCPenney", category: "catch-all", color: "#E31837" },
  { id: "kohl", name: "Kohl's", category: "catch-all", color: "#000000" },
  { id: "dillard", name: "Dillard's", category: "catch-all", color: "#000000" },
  { id: "bloomingdales", name: "Bloomingdale's", category: "catch-all", color: "#000000" },
  { id: "saks", name: "Saks Fifth Avenue", category: "catch-all", color: "#000000" },
  { id: "neiman_marcus", name: "Neiman Marcus", category: "catch-all", color: "#000000" },
  { id: "michaels", name: "Michaels", category: "catch-all", color: "#E31837" },
  { id: "joann", name: "JOANN", category: "catch-all", color: "#005CAB" },

  // ── Gas Stations ──
  { id: "shell", name: "Shell", category: "gas", color: "#FBCE07" },
  { id: "exxon", name: "Exxon", category: "gas", color: "#C8102E" },
  { id: "chevron", name: "Chevron", category: "gas", color: "#00549A" },
  { id: "bp", name: "BP", category: "gas", color: "#009900" },
  { id: "speedway", name: "Speedway", category: "gas", color: "#E31837" },
  { id: "wawa", name: "Wawa", category: "gas", color: "#C8102E" },
  { id: "qt", name: "QuikTrip", category: "gas", color: "#E31837" },
  { id: "sheetz", name: "Sheetz", category: "gas", color: "#DA291C" },
  { id: "circle_k", name: "Circle K", category: "gas", color: "#D71920" },
  { id: "marathon", name: "Marathon", category: "gas", color: "#005CAB" },
  { id: "sunoco", name: "Sunoco", category: "gas", color: "#FED100" },
  { id: "seven_eleven", name: "7-Eleven", category: "gas", color: "#F7941D" },
  { id: "racetrac", name: "RaceTrac", category: "gas", color: "#FCAF17" },
  { id: "caseys", name: "Casey's", category: "gas", color: "#E31837" },
  { id: "murphy_usa", name: "Murphy USA", category: "gas", color: "#00529B" },
  { id: "costco_gas", name: "Costco Gas", category: "gas", color: "#E31837" },
  { id: "bucees", name: "Buc-ee's", category: "gas", color: "#FFC72C" },
  { id: "pilot", name: "Pilot Flying J", category: "gas", color: "#D00000" },
  { id: "loves", name: "Love's Travel Stops", category: "gas", color: "#FFC20E" },

  // ── Travel (Airlines, Hotels, Car Rentals) ──
  { id: "delta", name: "Delta Air Lines", category: "travel", color: "#E3132C" },
  { id: "american_airlines", name: "American Airlines", category: "travel", color: "#1782D2" },
  { id: "united", name: "United Airlines", category: "travel", color: "#005DAA" },
  { id: "southwest", name: "Southwest Airlines", category: "travel", color: "#111B54" },
  { id: "jetblue", name: "JetBlue", category: "travel", color: "#003876" },
  { id: "alaska_airlines", name: "Alaska Airlines", category: "travel", color: "#01426A" },
  { id: "spirit", name: "Spirit Airlines", category: "travel", color: "#FFD200" },
  { id: "frontier", name: "Frontier Airlines", category: "travel", color: "#006341" },
  { id: "hawaiian", name: "Hawaiian Airlines", category: "travel", color: "#4A1E6D" },
  { id: "allegiant", name: "Allegiant Air", category: "travel", color: "#F7941D" },
  { id: "marriott", name: "Marriott", category: "travel", color: "#B8143F" },
  { id: "hilton", name: "Hilton", category: "travel", color: "#003A70" },
  { id: "hyatt", name: "Hyatt", category: "travel", color: "#0F2D52" },
  { id: "ihg", name: "IHG", category: "travel", color: "#D96932" },
  { id: "wyndham", name: "Wyndham", category: "travel", color: "#00A4D6" },
  { id: "best_western", name: "Best Western", category: "travel", color: "#00529B" },
  { id: "airbnb", name: "Airbnb", category: "travel", color: "#FF5A5F" },
  { id: "expedia", name: "Expedia", category: "travel", color: "#FDB813" },
  { id: "booking_com", name: "Booking.com", category: "travel", color: "#003580" },
  { id: "priceline", name: "Priceline", category: "travel", color: "#0068EF" },
  { id: "kayak", name: "KAYAK", category: "travel", color: "#FF690F" },
  { id: "turo", name: "Turo", category: "travel", color: "#593CFB" },
  { id: "enterprise", name: "Enterprise", category: "travel", color: "#006C5B" },
  { id: "hertz", name: "Hertz", category: "travel", color: "#FFD700" },
  { id: "avis", name: "Avis", category: "travel", color: "#D50032" },
  { id: "national", name: "National Car Rental", category: "travel", color: "#006400" },

  // ── Transit & Rideshare ──
  { id: "uber", name: "Uber", category: "transit", color: "#000000" },
  { id: "lyft", name: "Lyft", category: "transit", color: "#FF00BF" },
  { id: "amtrak", name: "Amtrak", category: "transit", color: "#004D79" },
  { id: "mta", name: "MTA (Subway & Bus)", category: "transit", color: "#0039A6" },
  { id: "nj_transit", name: "NJ Transit", category: "transit", color: "#F18A00" },
  { id: "bart", name: "BART", category: "transit", color: "#0099CC" },
  { id: "lime", name: "Lime", category: "transit", color: "#00FF00" },
  { id: "bird", name: "Bird", category: "transit", color: "#000000" },
  { id: "caltrain", name: "Caltrain", category: "transit", color: "#E31837" },
  { id: "wmata", name: "WMATA (DC Metro)", category: "transit", color: "#D4901E" },
  { id: "cta", name: "CTA (Chicago L)", category: "transit", color: "#00A1DE" },
  { id: "mbta", name: "MBTA", category: "transit", color: "#003DA5" },
  { id: "spin", name: "Spin", category: "transit", color: "#F97316" },
  { id: "zipcar", name: "Zipcar", category: "transit", color: "#006400" },

  // ── Streaming & Subscriptions ──
  { id: "netflix", name: "Netflix", category: "streaming", color: "#E50914" },
  { id: "spotify", name: "Spotify", category: "streaming", color: "#1DB954" },
  { id: "hulu", name: "Hulu", category: "streaming", color: "#1CE783" },
  { id: "disney_plus", name: "Disney+", category: "streaming", color: "#113CCF" },
  { id: "hbo_max", name: "Max (HBO)", category: "streaming", color: "#5400D5" },
  { id: "apple_tv", name: "Apple TV+", category: "streaming", color: "#000000" },
  { id: "youtube_tv", name: "YouTube TV", category: "streaming", color: "#FF0000" },
  { id: "peacock", name: "Peacock", category: "streaming", color: "#0E0E0E" },
  { id: "paramount_plus", name: "Paramount+", category: "streaming", color: "#0064FF" },
  { id: "amazon_prime", name: "Amazon Prime", category: "streaming", color: "#00A8E1" },

  // ── Drugstores & Pharmacies ──
  { id: "cvs", name: "CVS Pharmacy", category: "drugstores", color: "#CC0000" },
  { id: "walgreens", name: "Walgreens", category: "drugstores", color: "#E31837" },
  { id: "rite_aid", name: "Rite Aid", category: "drugstores", color: "#0033A0" },
  { id: "duane_reade", name: "Duane Reade", category: "drugstores", color: "#E31837" },
  { id: "costco_pharmacy", name: "Costco Pharmacy", category: "drugstores", color: "#E31837" },
  { id: "walmart_pharmacy", name: "Walmart Pharmacy", category: "drugstores", color: "#0071CE" },
  { id: "amazon_pharmacy", name: "Amazon Pharmacy", category: "drugstores", color: "#FF9900" },
  { id: "goodrx", name: "GoodRx", category: "drugstores", color: "#FFD60A" },

  // ── Convenience Stores & Dollar Stores ──
  { id: "dollar_general", name: "Dollar General", category: "catch-all", color: "#FFC300" },
  { id: "dollar_tree", name: "Dollar Tree", category: "catch-all", color: "#008C45" },
  { id: "family_dollar", name: "Family Dollar", category: "catch-all", color: "#FF6600" },
  { id: "five_below", name: "Five Below", category: "catch-all", color: "#003DA5" },
  { id: "99_cents", name: "99 Cents Only", category: "catch-all", color: "#FFD700" },

  // ── Home Improvement & Hardware ──
  { id: "menards", name: "Menards", category: "catch-all", color: "#006400" },
  { id: "ace_hardware", name: "Ace Hardware", category: "catch-all", color: "#C8102E" },
  { id: "harbor_freight", name: "Harbor Freight", category: "catch-all", color: "#E31837" },
  { id: "northern_tool", name: "Northern Tool", category: "catch-all", color: "#003DA5" },
  { id: "floor_decor", name: "Floor & Decor", category: "catch-all", color: "#2D5E1E" },
  { id: "sherwin_williams", name: "Sherwin-Williams", category: "catch-all", color: "#005CAB" },
  { id: "benjamin_moore", name: "Benjamin Moore", category: "catch-all", color: "#1B3C6E" },
  { id: "fastenal", name: "Fastenal", category: "catch-all", color: "#003DA5" },
  { id: "tractor_supply", name: "Tractor Supply Co.", category: "catch-all", color: "#CE1141" },

  // ── Electronics & Tech ──
  { id: "micro_center", name: "Micro Center", category: "catch-all", color: "#E31837" },
  { id: "bh_photo", name: "B&H Photo", category: "catch-all", color: "#000000" },
  { id: "samsung", name: "Samsung", category: "catch-all", color: "#034EA2" },
  { id: "dell", name: "Dell", category: "catch-all", color: "#007DB8" },
  { id: "hp", name: "HP", category: "catch-all", color: "#0096D6" },
  { id: "lenovo", name: "Lenovo", category: "catch-all", color: "#E2231A" },
  { id: "microsoft_store", name: "Microsoft Store", category: "catch-all", color: "#737373" },

  // ── Auto Repair & Service ──
  { id: "jiffy_lube", name: "Jiffy Lube", category: "gas", color: "#E31837" },
  { id: "valvoline", name: "Valvoline", category: "gas", color: "#003DA5" },
  { id: "maaco", name: "Maaco", category: "gas", color: "#0033A0" },
  { id: "midas", name: "Midas", category: "gas", color: "#FFD700" },
  { id: "pep_boys", name: "Pep Boys", category: "gas", color: "#E31837" },
  { id: "discount_tire", name: "Discount Tire", category: "gas", color: "#C8102E" },
  { id: "autozone", name: "AutoZone", category: "gas", color: "#E31837" },
  { id: "oreilly", name: "O'Reilly Auto Parts", category: "gas", color: "#006400" },
  { id: "advance_auto", name: "Advance Auto Parts", category: "gas", color: "#E31837" },
  { id: "napa", name: "NAPA Auto Parts", category: "gas", color: "#003DA5" },
  { id: "firestone", name: "Firestone", category: "gas", color: "#D22630" },
  { id: "goodyear", name: "Goodyear", category: "gas", color: "#003DA5" },
  { id: "take5", name: "Take 5 Oil Change", category: "gas", color: "#003A70" },
  { id: "safelite", name: "Safelite AutoGlass", category: "gas", color: "#00529B" },
  { id: "carmax", name: "CarMax", category: "gas", color: "#003DA5" },
  { id: "carvana", name: "Carvana", category: "gas", color: "#00AEF0" },

  // ── Fitness & Gym ──
  { id: "planet_fitness", name: "Planet Fitness", category: "catch-all", color: "#5D2D91" },
  { id: "la_fitness", name: "LA Fitness", category: "catch-all", color: "#E31837" },
  { id: "anytime_fitness", name: "Anytime Fitness", category: "catch-all", color: "#9B2335" },
  { id: "equinox", name: "Equinox", category: "catch-all", color: "#000000" },
  { id: "orangetheory", name: "Orangetheory Fitness", category: "catch-all", color: "#F36F21" },
  { id: "crossfit", name: "CrossFit", category: "catch-all", color: "#C8102E" },
  { id: "ymca", name: "YMCA", category: "catch-all", color: "#E31837" },
  { id: "peloton", name: "Peloton", category: "streaming", color: "#000000" },
  { id: "f45", name: "F45 Training", category: "catch-all", color: "#00A3E0" },
  { id: "crunch_fitness", name: "Crunch Fitness", category: "catch-all", color: "#003DA5" },
  { id: "lifetime_fitness", name: "Life Time Fitness", category: "catch-all", color: "#000000" },
  { id: "golds_gym", name: "Gold's Gym", category: "catch-all", color: "#FFD700" },
  { id: "24_hour_fitness", name: "24 Hour Fitness", category: "catch-all", color: "#0046BE" },
  { id: "barre3", name: "barre3", category: "catch-all", color: "#000000" },
  { id: "solidcore", name: "[solidcore]", category: "catch-all", color: "#000000" },
  { id: "barry_bootcamp", name: "Barry's Bootcamp", category: "catch-all", color: "#C8102E" },
  { id: "soulcycle", name: "SoulCycle", category: "catch-all", color: "#FFD700" },

  // ── Furniture & Home ──
  { id: "ashley_furniture", name: "Ashley Furniture", category: "catch-all", color: "#5C2D91" },
  { id: "rooms_to_go", name: "Rooms To Go", category: "catch-all", color: "#003DA5" },
  { id: "la_z_boy", name: "La-Z-Boy", category: "catch-all", color: "#003E69" },
  { id: "ethan_allen", name: "Ethan Allen", category: "catch-all", color: "#000000" },
  { id: "west_elm", name: "West Elm", category: "catch-all", color: "#000000" },
  { id: "cb2", name: "CB2", category: "catch-all", color: "#000000" },
  { id: "pier_one", name: "Pier 1", category: "catch-all", color: "#003DA5" },
  { id: "world_market", name: "World Market", category: "catch-all", color: "#8B4513" },
  { id: "bed_bath", name: "Bed Bath & Beyond", category: "catch-all", color: "#005CAB" },
  { id: "container_store", name: "The Container Store", category: "catch-all", color: "#005CAB" },
  { id: "at_home", name: "At Home", category: "catch-all", color: "#6AAE4C" },
  { id: "hobby_lobby", name: "Hobby Lobby", category: "catch-all", color: "#006341" },

  // ── Home Services ──
  { id: "terminix", name: "Terminix", category: "catch-all", color: "#003DA5" },
  { id: "orkin", name: "Orkin", category: "catch-all", color: "#E21837" },
  { id: "stanley_steemer", name: "Stanley Steemer", category: "catch-all", color: "#003A70" },
  { id: "roto_rooter", name: "Roto-Rooter", category: "catch-all", color: "#003DA5" },
  { id: "servpro", name: "SERVPRO", category: "catch-all", color: "#F7941D" },
  { id: "aaa", name: "AAA", category: "catch-all", color: "#003DA5" },

  // ── Childcare & Education ──
  { id: "kindercare", name: "KinderCare", category: "catch-all", color: "#E31837" },
  { id: "bright_horizons", name: "Bright Horizons", category: "catch-all", color: "#0072CE" },
  { id: "kumon", name: "Kumon", category: "catch-all", color: "#003DA5" },
  { id: "sylvan", name: "Sylvan Learning", category: "catch-all", color: "#006341" },
  { id: "mathnasium", name: "Mathnasium", category: "catch-all", color: "#E31837" },
  { id: "the_goddard_school", name: "The Goddard School", category: "catch-all", color: "#003A70" },

  // ── Pet & Vet ──
  { id: "banfield", name: "Banfield Pet Hospital", category: "catch-all", color: "#0033A0" },
  { id: "vca", name: "VCA Animal Hospital", category: "catch-all", color: "#005DAA" },
  { id: "pet_valu", name: "Pet Valu", category: "catch-all", color: "#006341" },
  { id: "petland", name: "Petland", category: "catch-all", color: "#008C15" },

  // ── Telecom & Utilities ──
  { id: "verizon", name: "Verizon", category: "catch-all", color: "#CD040B" },
  { id: "att", name: "AT&T", category: "catch-all", color: "#009FDB" },
  { id: "tmobile", name: "T-Mobile", category: "catch-all", color: "#E20074" },
  { id: "comcast", name: "Comcast/Xfinity", category: "catch-all", color: "#000000" },
  { id: "spectrum", name: "Spectrum", category: "catch-all", color: "#004282" },
  { id: "cox_comms", name: "Cox Communications", category: "catch-all", color: "#E87722" },
  { id: "centurylink", name: "CenturyLink", category: "catch-all", color: "#00A651" },
  { id: "frontier_comms", name: "Frontier Communications", category: "catch-all", color: "#E31837" },
  { id: "google_fi", name: "Google Fi", category: "catch-all", color: "#4285F4" },
  { id: "mint_mobile", name: "Mint Mobile", category: "catch-all", color: "#00B140" },
  { id: "visible", name: "Visible", category: "catch-all", color: "#120A8F" },
  { id: "cricket", name: "Cricket Wireless", category: "catch-all", color: "#7CC040" },
  { id: "metro_by_t", name: "Metro by T-Mobile", category: "catch-all", color: "#8E2D8E" },
  { id: "boost_mobile", name: "Boost Mobile", category: "catch-all", color: "#F36F21" },
  { id: "us_cellular", name: "US Cellular", category: "catch-all", color: "#003DA5" },

  // ── Delivery Services ──
  { id: "shipt", name: "Shipt", category: "groceries", color: "#00B050" },
  { id: "amazon_fresh", name: "Amazon Fresh", category: "groceries", color: "#FF9900" },
  { id: "gopuff", name: "Gopuff", category: "groceries", color: "#003DA5" },
  { id: "postmates", name: "Postmates", category: "dining", color: "#000000" },
  { id: "seamless", name: "Seamless", category: "dining", color: "#FF6600" },
  { id: "caviar", name: "Caviar", category: "dining", color: "#FF3008" },

  // ── Beauty & Personal Care ──
  { id: "bath_body_works", name: "Bath & Body Works", category: "catch-all", color: "#003DA5" },
  { id: "great_clips", name: "Great Clips", category: "catch-all", color: "#003DA5" },
  { id: "supercuts", name: "Supercuts", category: "catch-all", color: "#E31837" },
  { id: "sport_clips", name: "Sport Clips", category: "catch-all", color: "#C8102E" },
  { id: "sally_beauty", name: "Sally Beauty", category: "catch-all", color: "#000000" },
  { id: "massage_envy", name: "Massage Envy", category: "catch-all", color: "#5C2D91" },
  { id: "european_wax", name: "European Wax Center", category: "catch-all", color: "#005CAB" },
  { id: "drybar", name: "Drybar", category: "catch-all", color: "#FFD700" },

  // ── Entertainment & Events ──
  { id: "amc_theatres", name: "AMC Theatres", category: "catch-all", color: "#C8102E" },
  { id: "regal_cinemas", name: "Regal Cinemas", category: "catch-all", color: "#5C2D91" },
  { id: "cinemark", name: "Cinemark", category: "catch-all", color: "#003DA5" },
  { id: "ticketmaster", name: "Ticketmaster", category: "catch-all", color: "#005DAA" },
  { id: "stubhub", name: "StubHub", category: "catch-all", color: "#003DA5" },
  { id: "seatgeek", name: "SeatGeek", category: "catch-all", color: "#469B3D" },
  { id: "vivid_seats", name: "Vivid Seats", category: "catch-all", color: "#FF6600" },
  { id: "six_flags", name: "Six Flags", category: "catch-all", color: "#E31837" },
  { id: "cedar_fair", name: "Cedar Fair", category: "catch-all", color: "#003DA5" },
  { id: "universal", name: "Universal Studios", category: "catch-all", color: "#000000" },
  { id: "disney_parks", name: "Disney Parks", category: "catch-all", color: "#003DA5" },
  { id: "dave_busters", name: "Dave & Buster's", category: "dining", color: "#003A70" },
  { id: "topgolf", name: "Topgolf", category: "catch-all", color: "#003DA5" },
  { id: "main_event", name: "Main Event", category: "catch-all", color: "#FF6600" },
  { id: "bowlero", name: "Bowlero", category: "catch-all", color: "#003DA5" },

  // ── More Streaming & Subscriptions ──
  { id: "youtube_premium", name: "YouTube Premium", category: "streaming", color: "#FF0000" },
  { id: "crunchyroll", name: "Crunchyroll", category: "streaming", color: "#F47521" },
  { id: "apple_music", name: "Apple Music", category: "streaming", color: "#FA233B" },
  { id: "amazon_music", name: "Amazon Music", category: "streaming", color: "#25D1DA" },
  { id: "tidal", name: "Tidal", category: "streaming", color: "#000000" },
  { id: "audible", name: "Audible", category: "streaming", color: "#F8991D" },
  { id: "kindle_unlimited", name: "Kindle Unlimited", category: "streaming", color: "#FF9900" },
  { id: "discovery_plus", name: "Discovery+", category: "streaming", color: "#003DA5" },
  { id: "amc_plus", name: "AMC+", category: "streaming", color: "#000000" },
  { id: "starz", name: "Starz", category: "streaming", color: "#000000" },
  { id: "espn_plus", name: "ESPN+", category: "streaming", color: "#C8102E" },
  { id: "fubo", name: "FuboTV", category: "streaming", color: "#1BACE4" },
  { id: "sling_tv", name: "Sling TV", category: "streaming", color: "#1C2541" },
  { id: "philo", name: "Philo", category: "streaming", color: "#005DAA" },

  // ── Cloud & Software Subscriptions ──
  { id: "icloud", name: "iCloud+", category: "streaming", color: "#3693F5" },
  { id: "google_one", name: "Google One", category: "streaming", color: "#4285F4" },
  { id: "dropbox", name: "Dropbox", category: "streaming", color: "#0061FF" },
  { id: "microsoft_365", name: "Microsoft 365", category: "streaming", color: "#D83B01" },
  { id: "adobe_cc", name: "Adobe Creative Cloud", category: "streaming", color: "#FF0000" },
  { id: "notion", name: "Notion", category: "streaming", color: "#000000" },
  { id: "canva", name: "Canva", category: "streaming", color: "#00C4CC" },
  { id: "chatgpt_plus", name: "ChatGPT Plus", category: "streaming", color: "#10A37F" },

  // ── Meal Kits & Food Boxes ──
  { id: "hellofresh", name: "HelloFresh", category: "groceries", color: "#96C93D" },
  { id: "blue_apron", name: "Blue Apron", category: "groceries", color: "#003DA5" },
  { id: "factor", name: "Factor", category: "groceries", color: "#006341" },
  { id: "everyplate", name: "EveryPlate", category: "groceries", color: "#FF6600" },
  { id: "home_chef", name: "Home Chef", category: "groceries", color: "#FFD700" },
  { id: "daily_harvest", name: "Daily Harvest", category: "groceries", color: "#2D5E1E" },
  { id: "hungryroot", name: "Hungryroot", category: "groceries", color: "#000000" },
  { id: "freshly", name: "Freshly", category: "groceries", color: "#00B050" },

  // ── Financial Services ──
  { id: "venmo", name: "Venmo", category: "catch-all", color: "#3D95CE" },
  { id: "cash_app", name: "Cash App", category: "catch-all", color: "#00D54B" },
  { id: "paypal", name: "PayPal", category: "catch-all", color: "#003087" },
  { id: "zelle", name: "Zelle", category: "catch-all", color: "#6C1CD3" },
  { id: "robinhood", name: "Robinhood", category: "catch-all", color: "#00C805" },
  { id: "coinbase", name: "Coinbase", category: "catch-all", color: "#0052FF" },
  { id: "fidelity", name: "Fidelity", category: "catch-all", color: "#006400" },
  { id: "schwab", name: "Charles Schwab", category: "catch-all", color: "#00A3E0" },
  { id: "vanguard", name: "Vanguard", category: "catch-all", color: "#721422" },
  { id: "sofi", name: "SoFi", category: "catch-all", color: "#003DA5" },

  // ── More Dining — Fast Casual & Regional ──
  { id: "jersey_mikes", name: "Jersey Mike's", category: "dining", color: "#0033A0" },
  { id: "jimmy_johns", name: "Jimmy John's", category: "dining", color: "#000000" },
  { id: "firehouse_subs", name: "Firehouse Subs", category: "dining", color: "#C8102E" },
  { id: "jason_deli", name: "Jason's Deli", category: "dining", color: "#006341" },
  { id: "mcalisters", name: "McAlister's Deli", category: "dining", color: "#1B3C6E" },
  { id: "zaxbys", name: "Zaxby's", category: "dining", color: "#003DA5" },
  { id: "culvers", name: "Culver's", category: "dining", color: "#003DA5" },
  { id: "whataburger", name: "Whataburger", category: "dining", color: "#F37321" },
  { id: "cookout", name: "Cook Out", category: "dining", color: "#E31837" },
  { id: "white_castle", name: "White Castle", category: "dining", color: "#003DA5" },
  { id: "del_taco", name: "Del Taco", category: "dining", color: "#E31837" },
  { id: "el_pollo_loco", name: "El Pollo Loco", category: "dining", color: "#FFD700" },
  { id: "church_chicken", name: "Church's Chicken", category: "dining", color: "#E31837" },
  { id: "long_john", name: "Long John Silver's", category: "dining", color: "#003DA5" },
  { id: "captain_ds", name: "Captain D's", category: "dining", color: "#003DA5" },
  { id: "golden_corral", name: "Golden Corral", category: "dining", color: "#8B6914" },
  { id: "bonefish", name: "Bonefish Grill", category: "dining", color: "#003A70" },
  { id: "carrabba", name: "Carrabba's", category: "dining", color: "#C8102E" },
  { id: "red_robin", name: "Red Robin", category: "dining", color: "#C8102E" },
  { id: "bob_evans", name: "Bob Evans", category: "dining", color: "#E31837" },
  { id: "steak_n_shake", name: "Steak 'n Shake", category: "dining", color: "#C8102E" },
  { id: "hardees", name: "Hardee's", category: "dining", color: "#E31837" },
  { id: "carls_jr", name: "Carl's Jr.", category: "dining", color: "#FFD700" },
  { id: "checkers", name: "Checkers/Rally's", category: "dining", color: "#000000" },
  { id: "qdoba", name: "QDOBA", category: "dining", color: "#8B0000" },
  { id: "moes_sw", name: "Moe's Southwest Grill", category: "dining", color: "#FFD700" },
  { id: "tropical_smoothie", name: "Tropical Smoothie Cafe", category: "dining", color: "#00A550" },
  { id: "jamba", name: "Jamba", category: "dining", color: "#8CC63F" },
  { id: "smoothie_king", name: "Smoothie King", category: "dining", color: "#E31837" },
  { id: "dutch_bros", name: "Dutch Bros", category: "dining", color: "#003DA5" },
  { id: "tim_hortons", name: "Tim Hortons", category: "dining", color: "#C8102E" },
  { id: "krispy_kreme", name: "Krispy Kreme", category: "dining", color: "#008C45" },
  { id: "insomnia_cookies", name: "Insomnia Cookies", category: "dining", color: "#5C2D91" },
  { id: "crumbl", name: "Crumbl Cookies", category: "dining", color: "#F178B6" },
  { id: "nothing_bundt", name: "Nothing Bundt Cakes", category: "dining", color: "#8B0000" },

  // ── More Grocery — Regional Chains ──
  { id: "lidl", name: "Lidl", category: "groceries", color: "#003DA5" },
  { id: "hy_vee", name: "Hy-Vee", category: "groceries", color: "#E31837" },
  { id: "winn_dixie", name: "Winn-Dixie", category: "groceries", color: "#E31837" },
  { id: "bi_lo", name: "Bi-Lo", category: "groceries", color: "#E31837" },
  { id: "hannaford", name: "Hannaford", category: "groceries", color: "#006341" },
  { id: "market_basket", name: "Market Basket", category: "groceries", color: "#C8102E" },
  { id: "stater_bros", name: "Stater Bros.", category: "groceries", color: "#C8102E" },
  { id: "vons", name: "Vons", category: "groceries", color: "#C8102E" },
  { id: "ralphs", name: "Ralphs", category: "groceries", color: "#D22630" },
  { id: "fry_food", name: "Fry's Food", category: "groceries", color: "#D22630" },
  { id: "smiths", name: "Smith's", category: "groceries", color: "#005CAB" },
  { id: "king_soopers", name: "King Soopers", category: "groceries", color: "#005CAB" },
  { id: "jewel_osco", name: "Jewel-Osco", category: "groceries", color: "#E31837" },
  { id: "acme_markets", name: "ACME Markets", category: "groceries", color: "#E31837" },
  { id: "save_mart", name: "Save Mart", category: "groceries", color: "#E31837" },
  { id: "natural_grocers", name: "Natural Grocers", category: "groceries", color: "#6AAE4C" },
  { id: "earth_fare", name: "Earth Fare", category: "groceries", color: "#006341" },
  { id: "lucky_supermarket", name: "Lucky Supermarket", category: "groceries", color: "#E31837" },

  // ── Bookstores & Office ──
  { id: "barnes_noble", name: "Barnes & Noble", category: "catch-all", color: "#354D27" },
  { id: "half_price_books", name: "Half Price Books", category: "catch-all", color: "#C8102E" },
  { id: "staples", name: "Staples", category: "catch-all", color: "#CC0000" },
  { id: "office_depot", name: "Office Depot", category: "catch-all", color: "#CC0000" },
  { id: "fedex_office", name: "FedEx Office", category: "catch-all", color: "#4D148C" },
  { id: "ups_store", name: "The UPS Store", category: "catch-all", color: "#351C15" },

  // ── Health & Wellness ──
  { id: "gnc", name: "GNC", category: "catch-all", color: "#003DA5" },
  { id: "vitamin_shoppe", name: "The Vitamin Shoppe", category: "catch-all", color: "#006341" },
  { id: "urgent_care", name: "Urgent Care", category: "catch-all", color: "#E31837" },
  { id: "minute_clinic", name: "MinuteClinic", category: "drugstores", color: "#CC0000" },
  { id: "labcorp", name: "Labcorp", category: "catch-all", color: "#003DA5" },
  { id: "quest_diag", name: "Quest Diagnostics", category: "catch-all", color: "#003DA5" },
  { id: "lenscrafters", name: "LensCrafters", category: "catch-all", color: "#000000" },
  { id: "pearle_vision", name: "Pearle Vision", category: "catch-all", color: "#003DA5" },
  { id: "warby_parker", name: "Warby Parker", category: "catch-all", color: "#003DA5" },

  // ── Jewelry & Watches ──
  { id: "tiffany", name: "Tiffany & Co.", category: "catch-all", color: "#0ABAB5" },
  { id: "kay_jewelers", name: "Kay Jewelers", category: "catch-all", color: "#000000" },
  { id: "zales", name: "Zales", category: "catch-all", color: "#000000" },
  { id: "jared", name: "Jared", category: "catch-all", color: "#000000" },
  { id: "pandora", name: "Pandora", category: "catch-all", color: "#000000" },
  { id: "cartier", name: "Cartier", category: "catch-all", color: "#8B0000" },
];

/**
 * Overwrites the local constants using an Over-The-Air JSON payload.
 */
export function injectOTAMerchants(newMerchants) {
  if (Array.isArray(newMerchants) && newMerchants.length > 0) {
    MERCHANT_DATABASE = newMerchants;
  }
}

/**
 * Heuristic keyword matcher for ultra-fast offline categorization.
 * Runs before the AI fallback to handle local merchants instantly.
 */
export function extractCategoryByKeywords(query) {
  if (!query) return null;
  const q = query.toLowerCase();

  const rules = [
    { cat: "dining", words: ["pizza", "burger", "grill", "cafe", "coffee", "restaurant", "pub", "tavern", "bistro", "diner", "steak", "sushi", "taco", "deli", "bakery", "bbq", "house", "kitchen", "bar", "lounge"] },
    { cat: "groceries", words: ["market", "grocery", "foods", "supermarket", "farm"] },
    { cat: "gas", words: ["gas", "auto", "tire", "oil", "service station", "car wash"] },
    { cat: "travel", words: ["airline", "motel", "inn", "hotel", "resort", "bed & breakfast"] },
    { cat: "transit", words: ["mta", "transit", "authority", "metro", "parking", "garage", "towing"] },
    { cat: "drugstores", words: ["pharmacy", "drugstore", "rx", "apothecary"] }
  ];

  for (const rule of rules) {
    for (const word of rule.words) {
      // Must be a whole word match (e.g., 'bar' matches 'Joe\'s Bar' but not 'Barclays')
      const regex = new RegExp(`\\b${word}\\b`, 'i');
      if (regex.test(q)) {
        return rule.cat;
      }
    }
  }

  return null;
}
